---
title: "Music Insights"
author: "MAkena Haroldson"
output: html_notebook
---

First, we need tidyverse to handle data importing and wrangling...

```{r}
install.packages("tidyverse")
library("tidyverse")

survey <- read_csv("https://raw.githubusercontent.com/introdsci/MusicSurvey/master/music-survey.csv")
preferences <- read_csv("https://raw.githubusercontent.com/introdsci/MusicSurvey/master/preferences-survey.csv")

nrow(preferences) #46
colnames(preferences) #timestamp, pseudonym, title\artist
levels(preferences$Timestamp) #NULL
#levels(preferences$4) 
View(preferences)
View(survey)

```

Cleaning Data
rename columns names to a consistant format
```{r}
view(survey)
colnames(survey)[colnames(survey)=="Timestamp"] <- "time_submitted"
colnames(survey)[colnames(survey)=="First, we are going to create a pseudonym for you to keep this survey anonymous (more or less). Which pseudonym generator would you prefer?"] <- "pseudonym_generator"
colnames(survey)[colnames(survey)=="Sex"] <- "sex"
colnames(survey)[colnames(survey)=="What is your pseudonym?"] <- "pseudonym"
colnames(survey)[colnames(survey)=="Year you were born (YYYY)"] <- "year_born"
colnames(survey)[colnames(survey)=="Major"] <- "academic_major"
colnames(survey)[colnames(survey)=="Academic Year"] <- "academic_level"
colnames(survey)[colnames(survey)=="Which musical instruments/talents do you play? (Select all that apply)"] <- "instrument_list"
colnames(survey)[colnames(survey)=="Artist"] <- "favorite_song_artist"
colnames(survey)[colnames(survey)=="Song"] <- "favorite_song"
colnames(survey)[colnames(survey)=="Link to song (on Youtube or Vimeo)"] <- "favorite_song_link"

colnames(survey)
View(survey)
```


Create a Person and Song table
tible: a dataframe
```{r}

library("dplyr")
library("tidyr")


Person <- tibble(time_submitted=survey$time_submitted, pseudonym =survey$pseudonym, pseudonym_generator=survey$pseudonym_generator, sex=survey$sex, year_born=survey$year_born, academic_level= survey$academic_level, academic_major=survey$academic_major )

Song <- tibble(pseudonym=survey$pseudonym,favorite_song=survey$favorite_song, favorite_song_artist=survey$favorite_song_artist, favorite_song_link=survey$favorite_song_link)


View(Person)
View(Song)

```
commit
